"""empty message

Revision ID: 4875e0a11084
Revises: fad652502fef
Create Date: 2021-05-26 15:28:29.539436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4875e0a11084'
down_revision = 'fad652502fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('genres', sa.Column('mdb_id', sa.Integer(), nullable=False))
    op.drop_column('movies', 'cast')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('cast', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('genres', 'mdb_id')
    # ### end Alembic commands ###
