"""empty message

Revision ID: 63f0371708d7
Revises: 99096e9b30c6
Create Date: 2021-05-29 19:19:09.061757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f0371708d7'
down_revision = '99096e9b30c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('backdrop', sa.String(), nullable=False))
    op.alter_column('movies', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('movies', 'backdrop')
    # ### end Alembic commands ###
