"""empty message

Revision ID: 99096e9b30c6
Revises: e199950fe9b9
Create Date: 2021-05-27 15:49:45.450235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99096e9b30c6'
down_revision = 'e199950fe9b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('backdrop', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'backdrop')
    # ### end Alembic commands ###
